DatabaseStructure:
  db_name: fine_tune_db
  generate_mode:
    collection: generate
    pin: data
    mode: generate_mode
    user_input: user_input
    language: language
    ai_tasks: ai_tasks
    final_tasks: final_tasks
    final_output: final_output
    summary: summary
    rate: rate
    comment: comment
    created_time: created_time
    creator: creator
  modify_mode:
    collection: modify
    pin: data
    mode: modify_mode
    user_input: user_input
    final_output: final_output
    summary: summary
    rate: rate
    comment: comment
    created_time: created_time
    creator: creator
  similarity_mode:
    collection: similarity
    pin: data
    mode: similarity_mode
    user_input: user_input
    similarity_type: type
    lhs: lhs
    rhs: rhs
    final_output: final_output
    rate: rate
    comment: comment
    created_time: created_time
    creator: creator
  viewer_mode:
    collection: viewer
    pin: data
    mode: viewer_mode
    data_id: data_id
    data_summary: data_summary
    viewer_rate: viewer_rate
    viewer_comment: viewer_comment
UserDbStructure:
    db_name: user_db
    collection: user_info
    user_name: user_name
    user_password: user_password # Hashed password
    salt: salt                   # Salt for hashing
    created_time: created_time
    last_login_time: last_login_time
    token: JWT_token
    token_create_time: token_create_time
    token_expire_time: token_expire_time