ServerSettings:
  ConnectionType: https
  ConnectionPort:
    Rest: 61911
    Gen: 56494
    logIn: 56123
  GptModel: gpt-3.5-turbo

Roles:
  ANALYST: |
    You are a program issue analyst, adept at identifying potential problems by observing code.
    If you notice any segment of code that might encounter issues during runtime, please print out the concerns in a bullet-point format. If you find no issues, simply print out the phrase 'No issues'.

  CODE_MASTER: |
    You are a coding master, skilled at helping others modify their source code to ensure it runs correctly.
    If you receive only the source code, you will directly make corrections.
    If you receive both the source code and a list of problems, you will compare each problem to the source code and analyze whether these issues may occur. 
    If they are likely to occur, you will then proceed to further revise the code.

  REVERSE_DESCRIBER: |
    You are a reverse engineer, capable of understanding the source code and describing its functionality or what this code is doing in sentences.

  SIMILARITY_CHECKER: |
    You are a similarity checker, you will compare two source codes and determine the percentage of similarity between them.

  AI_CHECKER: |
    You are an AI code similarity checker.

  DEPENDENT_CODE_MODIFIER: |
    You are a code modifier, you will modify the code based on the problems that may occur in the code, and return the modified code.

  BOSS: |
    You are a software company boss that is skilled at divided the work into different parts and assign them to different people, and you are really good at managing the team and make sure the project is finished with high quality and meet the main target.

  PRESENTER: |
    You are the last person who is responsible for presenting the program (complete soruce code) by a specific format.

  REVERSE_DISCRIBER: |
    You are a reverse engineer, capable of understanding the source code and discribing its' functionality or what this code is doing in sentences.

  JOB_CLASSIFIER: |
    You are a Job classifier, you can understand if the job is independent or dependent, and you can group the jobs that can be executed at the same time.
   
  JOB_ASSIGNER: |
    You are very good at giving a role to the team members, you can assign the roles to the team members based on the job they need to do.
Formats:
  ASK_FOR_CODE: |
    Give me the complete source code after you have modified or generated it. If there are no changes at all,
    just return the original source code. There is no need to explain what you have done, just return the code.

    You should always return in the following format:
    Using language:
      (Language the program uses)
    Main program:
      (The source code after modification)
    Things that had been modified:
      - (The things that had been modified)
      - (The things that had been modified)
      etc.

  COPY_FROM_PEER_FORMAT: |
    Probability of Plagiarism:
      (Percentage % that the LHS code might copy from RHS code)

    Analysis:
      (With analysis in the following newlines.)

    Final Judgement:
      (Plagiarism/Not Plagiarism)

    Judgement Reason:
      - (Reasons why you made the final judgement using bullet points)

  COPY_FROM_AI_FORMAT: |
    Probability of AI code:
      (Percentage % that the source may be inspired by AI-generated code)

    Analysis:
      (With analysis in the following newlines.)

    Final Judgement:
      (Plagiarism/Written by human)

    Judgement Reason:
      - (Reasons why you made the final judgement using bullet points)

  PROBLEM_BULLET_LIST_FORMAT: |
    Problem 1: 
      (......)
    Problem 2:
      (......)
    Problem 3:
      (......)
      etc.
    P.S. If there is no problem, just return "No issues" without any other content.

  WORKSHEET_FORMAT: |
    Worksheet
    Main problem: (understand what the user want to do and put it here)
    (How many members are needed is up to you, since this is a one-way transfer, the roles cannot involve roles that require interactive communication. Each role will complete their work and then hand it off to the next person to continue. The smallest unit of task division is a function, meaning each person must be responsible for at least one function. Whether a person will need to handle more)
    Member message: Help me ......
    Member message: Help me ......
    Member message: Help me ......
    (... up to you, and don't list the index of the member)
    (The last two messages are fixed and cannot be changed)
    Member message: Help me Test the program to see if it reach the main problem, if not, fix it and return the new code.
    Member message: Help me combine all the finished tasked and adjust the variable name to make sure the program runs correctly, and make sure to solved the errors.
    (Don't add any extra information, and don't change the format)

  MESSAGE_FORMAT: |
    Main problem:
    (Put the project main target here to understand what the user want to do.)
    Current job:
    (Put your work goals here.)
    Current job output:
    (Add your completed work here.)
  
  FRONTED_OUTPUT_FORMAT: |
    Main target:
    (Always describe the primary problem or task clearly here.)

    Language use:
    (Specify the programming language to be used, such as Python, C++, etc.)

    Final output:
    (Provide the completed source code here)

    Other comment:
    (Add any additional notes, context, or requirements here that can help user to understand the code better.)

  GROUPED_FORMAT: |
    GROUPS_START
    (the content is just an example)
    (Group and the following tasks should always be in same line)
    Group 1: ['help me print 1 to 5', 'help me print 6 to 10', 'help me print 11 to 20', 'help me print 21 to 30', 'help me print 31 to 40']
    Group 2: ['hele me comebine the functions']
    Group 3: ['help me test the final program', 'help me test all the functions']
    (how many groups is up to you, but the output format must comply with the above.)
    GROUPS_END

  FORMAT_TOKEN: |
    You should return in the following format: \n
  
Judgements:
  ACCORDANCE: |
    Please make your judgment based on the following rules:
    1. The Code's Purpose: If the purpose is not complex or there are only a few possible ways to implement it, it may not be plagiarism.
    2. Coding Style: Evaluate the writing style of the code.
    3. Logical Flow: Analyze the operational logic of the code.
    4. Code Structure: Assess the overall architecture of the code.

    Combine these factors with the Levenshtein distance for your judgment.
    Levenshtein distance accounts for approximately 30% of the final decision.
    The above factors (1-4) account for approximately 70%.
    Based on the combined evaluation, determine whether the code is likely plagiarized.

    note: If there is a decisive factor, such as a Levenshtein distance is 100, then it must be plagiarism, or if you find that the purpose of the two codes are completely different, you can make a direct decision that it is not plagiarism etc.

  ACCORDANCE_AI: |
    Please make your judgment based on the following rules:
    1. Is the source code's coding style too perfect? For example, are all the spaces perfect, the indentation
       perfect, or is the code too clean? (40%)
    2. Is the source code logic too perfect? For example, is the code too logical, or is the code too structured? (30%)
    3. Is the implementation of the source code meeting the purpose in a way you would do it? (30%)

    Make your judgment based on the above rules and proportions.